clone:
  depth: full
  lfs: true
pipelines:
  default:
    - step:
        script:
          - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
          - apt-get -y install git-lfs zip
          - git clone --mirror git@bitbucket.org:olibd92/deepvisualodometry.git
          - cd deepvisualodometry.git
          - git push --mirror git@github.com:olibd/deepvisualodometry_mirror.git