name: dvo
channels:
  - pytorch
  - defaults
dependencies:
  - cuda100
  - cudatoolkit=10.1
  - cudnn
  - python=3.6.10
  - pip==20.2.2
  - pytorch==1.6.0
  - torchvision==0.7.0
  - pip:
    - numpy==1.19.2
    - pandas==1.1.2
    - pillow==6.2.2
    - matplotlib==3.3.2
    - glob3==0.0.1
    - scipy==1.4.1
    - h5py==2.10.0
    - comet_ml==3.2.2
    - pyquaternion==0.9.5
    - gitpython==3.1.8
    - stopit==1.1.2
    - ffmpeg-python==0.2.0

